---
- hosts: pilote
  gather_facts: true
  tasks:
    - ansible.builtin.include_tasks: tasks/sysctl.yml
    - ansible.builtin.include_tasks: tasks/apt.yml
    - ansible.builtin.include_tasks: tasks/users.yml
    - ansible.builtin.include_tasks: tasks/profile.yml
    - ansible.builtin.include_tasks: tasks/hostname.yml
    - ansible.builtin.include_tasks: tasks/motd.yml
    - ansible.builtin.include_tasks: tasks/time.yml
    - ansible.builtin.include_tasks: tasks/ssh.yml
    - ansible.builtin.include_tasks: tasks/openvpn.yml
    - ansible.builtin.include_tasks: tasks/nagios.yml
    - ansible.builtin.include_tasks: tasks/nrpe.yml
    - ansible.builtin.include_tasks: tasks/mosquitto.yml
    - ansible.builtin.include_tasks: tasks/serial2mqtt.yml
    - ansible.builtin.include_tasks: tasks/telegraf.yml
    - ansible.builtin.include_tasks: tasks/bacula.yml
    - ansible.builtin.include_tasks: tasks/iptables.yml
    # TODO
    #- ansible.builtin.include_tasks: tasks/easyrsa.yml
    - ansible.builtin.include_tasks: tasks/vim.yml
