---
- name: Remove useless packages
  ansible.builtin.apt:
    name:
      - wpasupplicant
      - pi-bluetooth
    state: absent

- name: Define repositories
  ansible.builtin.template:
    src: apt/raspi.list.j2
    dest: /etc/apt/sources.list.d/raspi.list

- name: Update system
  ansible.builtin.apt:
    update_cache: 'yes'
    upgrade: 'yes'
