---
- name: Install figlet
  ansible.builtin.package:
    name: figlet
    state: present

- name: Run figlet
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail
      hostname | figlet -f /usr/share/figlet/smslant.flf
    executable: /bin/bash
  register: _motd
  changed_when: true

- name: Create motd
  ansible.builtin.copy:
    dest: /etc/motd
    content: "{{ _motd.stdout }}\n"
    mode: "0644"
